version: '3'

services:
  youtubeshell:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: myenvpro
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
        #command: sh -c "apt update && apt install -y vlc && vlc"
