version: '3'

services:
  youtubeshell:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: youshell
    stdin_open: true
    tty: true
    env_file:
      - .env_example
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
